sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  - npm i -g npm@5.3.0
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ./.npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
install:
   - npm install
script:
  - NODE_ENV=production npm run build
after_success:
  - npm run semantic-release
  - npm run website-update
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
