// ACTIONS project
export const NEW_PROJECT = 'NEW_PROJECT';
export const LOAD_PROJECT = 'LOAD_PROJECT';
export const SAVE_PROJECT = 'SAVE_PROJECT';
export const LOAD_PROJECT_FROM_FILE = 'LOAD_PROJECT_FROM_FILE';
export const SAVE_PROJECT_TO_FILE = 'SAVE_PROJECT_TO_FILE';

// ACTIONS editing
export const SELECT_TOOL_EDIT = 'SELECT_TOOL_EDIT';

// ACTIONS viewer2d
export const SELECT_TOOL_ZOOM_IN = 'SELECT_TOOL_ZOOM_IN';
export const SELECT_TOOL_ZOOM_OUT = 'SELECT_TOOL_ZOOM_OUT';
export const SELECT_TOOL_PAN = 'SELECT_TOOL_PAN';
export const UPDATE_2D_CAMERA = 'UPDATE_2D_CAMERA';

//ACTIONS viewer3d
export const SELECT_TOOL_3D_VIEW = 'SELECT_TOOL_3D_VIEW';

//MODES
export const MODE_IDLE = 'IDLE';
export const MODE_2D_ZOOM_IN = 'MODE_2D_ZOOM_IN';
export const MODE_2D_ZOOM_OUT = 'MODE_2D_ZOOM_OUT';
export const MODE_2D_PAN = 'MODE_2D_PAN';
export const MODE_3D_VIEW = 'MODE_3D_VIEW';
